### ISSUE TITLE
Garlic 2.0 not booting

### ISSUE THREAD

**Issue by informadortech** [GarlicOS/bootloader_anbernic_rg35xxplus#1]
Hi,

I am trying to test Garlic 2.0 on my new RG35XX Plus.
- I've extracted the bootloader files to the root of original SD card and placed it on the TF1 slot

![Screenshot_37](https://github.com/GarlicOS/bootloader_anbernic_rg35xxplus/assets/65343528/df59c8ee-a843-4f91-ae78-9e94c20318e1)

- I've formatted another sd card in extFAT, created boot folder and placed init and rootfs.f2fs files (extrated from armhf-rootfs.7z). Placed it on TF2.

![Screenshot_38](https://github.com/GarlicOS/bootloader_anbernic_rg35xxplus/assets/65343528/300b4335-43ad-47a3-8135-b3f7e0e494b5)

I boot my RG35XX+ by pressing power button only, it show the Anbernic boot logo and than it appear to shutdown. The top LED is off and nothing happens. If I remove the TF2 card it boot to original OS. Any thought what I'm doing wrong?

**Comment by 333mhz** [comment]
I success by following instrustion step by step and my tf2 is fat32 format.
Your problem may be solved by:
1.try download [init_template](https://github.com/GarlicOS/init_template/blob/main/init) directly to avoid text format problem.
2.Reinsert TF2, 35xxplus tf2 slot  is annoying defective sometimes.
3.Check tf2 on windows diskmgmt.msc, delete all partition and format agian.

**Comment by informadortech** [comment]
> I success by following instrustion step by step and my tf2 is fat32 format. Your problem may be solved by: 1.try download [init_template](https://github.com/GarlicOS/init_template/blob/main/init) directly to avoid text format problem. 2.Reinsert TF2, 35xxplus tf2 slot is annoying defective sometimes. 3.Check tf2 on windows diskmgmt.msc, delete all partition and format agian.

Thanks, it's running and I tested with FAT32 and ExtFAT and both work. Maybe I was putting the init file wrong.

Will close the issue.

**Comment by zdx1012** [comment]
I have also operated like you, but it still cannot start and always enters the native system. Do you still need to delete any content from the TF card?

**Comment by zdx1012** [comment]
> I have also operated like you, but it still cannot start and always enters the native system. Do you still need to delete any content from the TF card?

ok, Maybe I using wrong TF Card .
