### ISSUE TITLE
Garlic OS boots but crashes every time I open anything

### ISSUE THREAD

**Issue by lungless-chest** [GarlicOS/bootloader_anbernic_rg35xxplus#17]
I installed GarlicOS 2.02 on my RG35XXSP and anytime I try to do anything, such as open the library, it instantly crashes and turns off.

**Comment by aloychan** [comment]
Did you happened to press the "A" and the screen just turn off?
Try pressing the "Y" button. I noticed it had replaced the function of the "A" button.

**Comment by lungless-chest** [comment]
This worked. Interesting that they would be swapped, not quite sure how that would happen. Thanks!
