### ISSUE TITLE
Not Booting

### ISSUE THREAD

**Issue by I3lackshirts** [GarlicOS/bootloader_anbernic_rg35xxplus#2]
I had an issues with the stock card and had to format. Is the stock card needed for the GalicOS to boot? I have been trying to use the Phoenix Card program to restore the stock OS img but it keeps freeze my computer and I am forced to rest. I am using Windows 11. Any suggestions to get the stock OS back?

**Comment by daylerees** [comment]
I've got it booting to a black screen and then turning off after the Anbernic Logo. To summarize what I have (and this is for an RG35XX+)

TF1: Flashed the stock firmware (64gb) from Anbernic's site to the card, and then added the boot loader files. There were actually two partitions on the stock card, and the docs didn't say which, so I added to both.

TF2: Formatted as ExFAT, created a 'boot' directory, and copied both the unzipped filesytem image and init script (no extension.. didn't mark as executable so will try that next.)

**Comment by Black-Seraph** [comment]
ARM devices and ARM64 devices with ARM userspace drivers (RG35XX, RG35XX+, RG35XXH) need to use the armhf rootfs.

ARM64 devices that require a ARM rootfs mention this explicitly in their bootloader repositories.

Given the recent update I figure this issue can be closed now.
