### ISSUE TITLE
Question about support

### ISSUE THREAD

**Issue by Masamune3210** [GarlicOS/bootloader_anbernic_rg35xxplus#5]
I figure I already know the answer to this, but figured it wouldn't hurt to make sure anyway. This won't work for the 35xx sans plus, correct? Or will it?

**Comment by Black-Seraph** [comment]
Not yet, but it will be added to the roster soon alongside with the next batch of devices.

**Comment by Masamune3210** [comment]
Can't wait! Thanks for letting me know
